sudo: false
dist: c7
language: ruby
cache: bundler
before_install:
- bundle -v
- rm Gemfile.lock || true
- gem update --system
- gem update bundler
- gem --version
- bundle -v
script:
- bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: "--without system_tests development"
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.2.7
    bundler_args: "--without system_tests development"
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.4
    bundler_args: "--without system_tests development"
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.4.1
    bundler_args: "--without system_tests development"
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: default
    bundler_args:
    sudo: required
    services: docker
    env: BEAKER_debug=1 PUPPET_INSTALL_TYPE=agent CHECK=beaker
branches:
  only:
  - master
  - "/^v\\d/"
notifications:
  email:
  - project@bendler-net.de
deploy:
  provider: puppetforge
  user: thbe
  password:
  - secure: QTNsy+l32K7+RoT3f6eBDfuKtgtGjeiMXeRF0KqWjurcf3+NFPWQ0sju3NJsQ+EALLum9eJqaN0woqbdRPwvVUBqk4quNnPsSZmS3EzDHZ0pSl3B23GEZRiL9HC7LGJmKgU6Fvs2AZE2PgMlqRUphuG716sZ8WuSOQITTLiwFCnA1obMSmJ+axYc7YZ605JUOA+ADzEr4rbOpZejxTdD2+Se+OnQ7+JZ6X/ec1XQllCZHs89pkrFdXDQLGMvvR2K90DDqGXiFDgkgeJ9znOo8fpv58/7SJjWKwSOH7acKWRpSqizPgOV6Ly6TFnp3Ku0Wz5VFvrleISS6FUdiygHqWaJ8J3UMDcslMmHqo+MDrQBX9pznqnBHeiv0DzuNMwYvAxrPULraNZe8h3yCOdc8/T/zWmqsLxdMeY/fn1wdRHAtUSZK1CPXaVxfi65H2fVQuNwIkhNrgH7kTICFEdwYqdTZhUzRQZhUkLXr7DpzllYNJEv8Ui+ofNsr0vDuMPFV9OumD04Fy0eC+yZOZDDKDsp2V73cIAboDWrvIYjkk6BTz/2LEcEMBelW+6yRfCSBbUQUNEnNFVGY0aReZGKyiHNzVEj6Sp6rRkeTi+Da2XwoumD1fBgW70OLtFVbL8WLnzBiGyF2mY0vhUg91aUgI811sA/VRN7tBgWf2jxU5E=
